//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dime
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DimeEntities : DbContext
    {
        public DimeEntities()
            : base("name=DimeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clanarina> Clanarinas { get; set; }
        public virtual DbSet<ClanarinaIgraca> ClanarinaIgracas { get; set; }
        public virtual DbSet<Igrac> Igracs { get; set; }
        public virtual DbSet<Klub> Klubs { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<StatistikaIgraca> StatistikaIgracas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TipTreninga> TipTreningas { get; set; }
        public virtual DbSet<TipUtakmice> TipUtakmice1 { get; set; }
        public virtual DbSet<Trening> Trenings { get; set; }
        public virtual DbSet<TreningPrisustvo> TreningPrisustvoes { get; set; }
        public virtual DbSet<UlogaKorisnika> UlogaKorisnikas { get; set; }
        public virtual DbSet<Utakmica> Utakmicas { get; set; }
    }
}
