//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dime
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatistikaIgraca
    {
        public int id_utakmice { get; set; }
        public int id_igraca { get; set; }
        public int minutaza { get; set; }
        public int sb_zabijeni { get; set; }
        public int sb_pokusaji { get; set; }
        public int p2_zabijeni { get; set; }
        public int p2_pokusaji { get; set; }
        public int p3_zabijeni { get; set; }
        public int p3_pokusaji { get; set; }
        public int asistencije { get; set; }
        public int skokovi { get; set; }
        public int prekrsaji { get; set; }
    
        public virtual Igrac Igrac { get; set; }
        public virtual Utakmica Utakmica { get; set; }
    }
}
