//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dime
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trening
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trening()
        {
            this.TreningPrisustva = new HashSet<TreningPrisustvo>();
        }
    
        public int id_trening { get; set; }
        public System.DateTime datum { get; set; }
        public System.TimeSpan vrijeme { get; set; }
        public string napomena { get; set; }
        public int tip_treninga { get; set; }
        public int korisnik { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual TipTreninga TipTreninga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreningPrisustvo> TreningPrisustva { get; set; }
    }
}
