//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dime
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utakmica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utakmica()
        {
            this.StatistikeIgraca = new HashSet<StatistikaIgraca>();
        }
    
        public int id_utakmica { get; set; }
        public System.DateTime datum { get; set; }
        public System.TimeSpan vrijeme { get; set; }
        public string opis { get; set; }
        public int zabijeni_poeni { get; set; }
        public int primljeni_poeni { get; set; }
        public int tip_utakmice { get; set; }
        public int protivnik { get; set; }
        public int korisnik { get; set; }
    
        public virtual Klub Protivnik { get; set; }
        public virtual Korisnik Korisnici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatistikaIgraca> StatistikeIgraca { get; set; }
        public virtual TipUtakmice TipUtakmice { get; set; }
    }
}
